#!/usr/bin/env bash
# Turn building the tests on or off. Default is off.

if [ -z $CLOCKS_ROOT_DIR ]; then
    echo "error: Environment not set up. Run setup."
    exit
fi

if [ -z $1 ]; then
    ctest
elif [ "$1" != "on" -a "$1" != "off" ]; then
    echo "error: Acceptible parameters are 'on' and 'off' "
    exit
else
    cd $CLOCKS_ROOT_DIR/build
    cmake -DBUILD_TEST=$1 ..
fi
